"""Added Tweet id index

Revision ID: 6d673ea37cf
Revises: None
Create Date: 2014-04-25 01:28:58.218000

"""

# revision identifiers, used by Alembic.
revision = '6d673ea37cf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tweet_id'), 'tweet', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweet_id'), table_name='tweet')
    ### end Alembic commands ###
